In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data_train  = pd.read_csv('emnist-letters-train.csv')
data_test = pd.read_csv('emnist-letters-test.csv')

In [3]:
X = data_train.drop('Y',axis = 1).values
X = X.T
X = X/255.0
y = data_train['Y'].values.reshape(data_train.shape[0],1)
print(y)


[[23]
 [ 7]
 [16]
 ...
 [ 1]
 [23]
 [12]]


In [4]:
X_test = data_test.drop('Y',axis = 1).values
X_test = X_test.T
X_test = X_test/255.0
y_test = data_test['Y'].values.reshape(data_test.shape[0],1)
print(y_test)



[[ 1]
 [ 1]
 [ 1]
 ...
 [19]
 [19]
 [19]]


In [5]:
Y_test = []
for i in range(26):
  t = []
  for j in range(14800):
      if y_test[j] == (i+1):
          t.append(1)
      else:
          t.append(0)
  Y_test.append(t)  


In [6]:
Y = []
for i in range(26):
  t = []
  for j in range(88800):
      if y[j] == (i+1):
          t.append(1)
      else:
          t.append(0)
  Y.append(t)      



In [9]:
iterations = 6000
alpha = 1
m = 88800
cost_values = []
trained_parameters = []

In [10]:
for tr in range (26):
    U = Y[tr]
    Z = np.array(U)
    weights = np.random.randn(1,784)
    bias = 0
    costfunc_values = []
    print('Training for datset' +str(tr))
    for i in range(0,iterations+1):
       z = np.dot(weights,X)+bias
       hy = 1/(1+np.exp(-z))
       j = 1/m*(-1*(np.sum(Z*np.log(hy)+(1-Z)*np.log(1-hy))))
       costfunc_values.append(j)
       dw = 1/m*np.dot(hy-Z,X.T)
       db = 1/m*np.sum(hy-Z)
       weights = weights -alpha*dw
       bias = bias - alpha*db
       if(i%350) == 0:
           print('running @',j)
    cost_values.append(costfunc_values)
    trained_parameters.append([weights,bias])
       

Training for datset0
running @ 3.476798178135336
running @ 0.15230806260790852
running @ 0.1281831095053652
running @ 0.11894099967585013
running @ 0.11411025099342241
running @ 0.1110675031334823
running @ 0.1089109491371224
running @ 0.1072636706022376
running @ 0.10594383722684604
running @ 0.10485308657243017
running @ 0.10393275450993515
running @ 0.10314480194631734
running @ 0.10246280953749135
running @ 0.10186742455366143
running @ 0.10134390232207795
running @ 0.10088068727203209
running @ 0.10046853799990058
running @ 0.10009995351404169
Training for datset1
running @ 3.5429647007295246
running @ 0.14373596762144344
running @ 0.11225750276297664
running @ 0.10138037768918587
running @ 0.09592520317416268
running @ 0.09257896015091353
running @ 0.09026786033556919
running @ 0.0885485638816507
running @ 0.0872033512824918
running @ 0.08611206054637041
running @ 0.08520285416393016
running @ 0.0844300508823465
running @ 0.083763044233297
running @ 0.08318037995226962
running @ 

C:\Users\Dell\AppData\Local\Temp\ipykernel_11696\4141458307.py:11: RuntimeWarning: divide by zero encountered in log
  j = 1/m*(-1*(np.sum(Z*np.log(hy)+(1-Z)*np.log(1-hy))))


running @ 0.11320780233135443
running @ 0.09311893652399295
running @ 0.08523683175425462
running @ 0.0808798992388655
running @ 0.0781407449844315
running @ 0.07627569806079318
running @ 0.0749267586961485
running @ 0.07390391268375245
running @ 0.07309909229045758
running @ 0.07244709881315776
running @ 0.07190651924842972
running @ 0.0714498452803855
running @ 0.07105808524655513
running @ 0.07071768530908253
running @ 0.07041869390176943
running @ 0.07015362465350464
running @ 0.06991672725337719
Training for datset5
running @ 1.3293941004074283
running @ 0.10158058925722933
running @ 0.0842121602249453
running @ 0.07745126090999022
running @ 0.07373630610835087
running @ 0.07135689636581509
running @ 0.06968231193152123
running @ 0.06842588382646855
running @ 0.0674389296028296
running @ 0.06663682174048184
running @ 0.06596796663324458
running @ 0.06539914647293534
running @ 0.06490795632383542
running @ 0.06447864719756792
running @ 0.06409973421027709
running @ 0.06376256943516

In [14]:
for i in range (26):
    U = Y[tr]
    Z = np.array(U)
    weights = trained_parameters[i][0]
    bias = trained_parameters[i][1]
    correct_predictions = 0
    for j in range(88800):
        z = np.dot(weights,X.T[j])+bias
        hypothesis = 1/(1+np.exp(-z))
        if np.logical_and(hypothesis >= 0.5,Z[j] == 1):
            correct_predictions+=1
        if np.logical_and(hypothesis <0.5 , Z[j] == 0):
            correct_predictions+=1
    acc = (correct_predictions/88800)
    print('accuracy for dataset' + str(i), "=" , acc)

accuracy for dataset0 = 0.9456644144144144
accuracy for dataset1 = 0.9383333333333334
accuracy for dataset2 = 0.9281756756756757
accuracy for dataset3 = 0.9405405405405406
accuracy for dataset4 = 0.9344594594594594
accuracy for dataset5 = 0.932240990990991
accuracy for dataset6 = 0.9474099099099099
accuracy for dataset7 = 0.9358671171171171
accuracy for dataset8 = 0.9327815315315315
accuracy for dataset9 = 0.9304504504504505
accuracy for dataset10 = 0.937240990990991
accuracy for dataset11 = 0.9350900900900901
accuracy for dataset12 = 0.9261936936936936
accuracy for dataset13 = 0.9378716216216216
accuracy for dataset14 = 0.9290315315315315
accuracy for dataset15 = 0.9280067567567568
accuracy for dataset16 = 0.9411261261261261
accuracy for dataset17 = 0.9381081081081081
accuracy for dataset18 = 0.9297635135135135
accuracy for dataset19 = 0.9470495495495496
accuracy for dataset20 = 0.935045045045045
accuracy for dataset21 = 0.9319256756756756
accuracy for dataset22 = 0.9268130630630631
a

In [12]:
y_pred = []
a = 0
for i in range (14800):
    probabilities = []
    for j in range(19):
        weights = trained_parameters[j][0]
        bias = trained_parameters[j][1]
        z = np.dot(weights,X_test.T[i]) +bias
        hypothesis = 1/(1+np.exp(-z))
        probabilities.append(hypothesis)
        
    predict = probabilities.index(max(probabilities))
    predict += 1
    y_pred.append(predict)
    
y_pred = np.array(y_pred)
y_pred = y_pred.T
print(y_pred)
 

[ 5  1  1 ... 19 10  3]


In [13]:
c = 0
for i in range(14800):
 if (y_pred[i] == y_test[i]):
  c +=1 
print("accuracy = ", c/14800)

accuracy =  0.7046621621621622
